name = "notes-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "USERS_KV"
id = "ecb99da83ceb4daabd3e382f9265f4b3"
preview_id = "c31908c6a09f47acb7e922be508ac243"

[vars]
